# Inserts a blank line between shell prompts
add_newline = true
# Pipes ╰─ ╭─
# Powerline symbols                                    

right_format = """\
$cmd_duration
"""

format = """
$username$hostname$directory
$character
"""

[username]
style_user = "fg:black bg:yellow bold"
style_root = "fg:red bg:yellow bold italic"
format = "[](yellow)[ $user ]($style)[](fg:yellow bg:black)"
disabled = false
show_always = true

[hostname]
format = "[ $hostname ](fg:white bg:black bold)[](fg:black bg:yellow)"
disabled = false
ssh_only = false

[directory]
truncation_length = 2
truncation_symbol = "./"
format = "[ $path ](fg:black bg:yellow bold)[$read_only ](fg:black bg:yellow bold)[](fg:yellow)"
read_only = "󰌾"
home_symbol = ""

[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[character]
success_symbol = "[](#ebcb8b)[  ➜  ](fg:#000000 bg:#ebcb8b bold)[ ](#ebcb8b)"
error_symbol = "[](#bf616a)[  ✖  ](fg:#000000 bg:#bf616a bold)[ ](#bf616a)"

[cmd_duration]
min_time = 0
format = "[](#ebcb8b)[ $duration ](bg:#ebcb8b fg:#000000 bold)[](#ebcb8b)"
